# Generated by Django 4.1.3 on 2022-11-19 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('major', models.CharField(blank=True, max_length=200, null=True)),
                ('year_start', models.CharField(blank=True, help_text='YYYY', max_length=4, null=True)),
                ('year_graduated', models.CharField(blank=True, help_text='YYYY', max_length=4, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumes.person')),
            ],
        ),
    ]
