# Generated by Django 4.1.3 on 2022-11-22 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=200, null=True)),
                ('employer', models.CharField(blank=True, max_length=200, null=True)),
                ('year_started', models.CharField(blank=True, help_text='MM/YYYY', max_length=8, null=True)),
                ('year_end', models.CharField(blank=True, help_text='MM/YYYY', max_length=8, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumes.person')),
            ],
        ),
    ]
