# Generated by Django 4.1.3 on 2022-11-26 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_name', models.CharField(blank=True, max_length=200, null=True)),
                ('cert_url', models.URLField(blank=True, null=True)),
                ('cert_author', models.CharField(blank=True, max_length=200, null=True)),
                ('year_awarded', models.CharField(blank=True, help_text='MM/YYYY', max_length=8, null=True)),
                ('year_expired', models.CharField(blank=True, help_text='MM/YYYY', max_length=8, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumes.person')),
            ],
        ),
    ]
